#pragma once

#include "memory/index.h"
#include "char/index.h"
#include "string/index.h"
#include "list/index.h"
#include "hash/index.h"
#include "vec/index.h"
#include "blob/index.h"
#include "file/index.h"
#include "array/index.h"
#include "stack/index.h"
#include "int/index.h"
#include "code/index.h"
#include "utf8/index.h"
#include "text/index.h"
#include "font/index.h"
#include "lexer/index.h"
#include "sexp/index.h"
#include "file/index.h"
#include "image/index.h"
#include "store/index.h"
#include "canvas/index.h"
#include "commander/index.h"

#include "modules_test.h"
