#pragma once

primitive_fn_t primitive_swap;
primitive_fn_t primitive_rot;

primitive_fn_t primitive_connect;
primitive_fn_t primitive_wire_print_net;
primitive_fn_t primitive_wire_pair;

primitive_fn_t primitive_run;
primitive_fn_t primitive_print_vm;
primitive_fn_t primitive_print_value_stack;
primitive_fn_t primitive_print_return_stack;

primitive_fn_t primitive_debug;
